#!/usr/bin/env ruby
IO.popen("sbt \"~ test\"") do |io|
  while(line = io.gets)
    if line.strip.match /All tests PASSED/
      puts line
      `growlnotify --image "images/scalalogo-green.png" --name "sbt" -t "sbt test" -m "Tests pass."`
	elsif line.strip.match /Error running test-compile: Compilation unsuccessful/
	  puts line
	  `growlnotify --image "images/scalalogo-red.png" --name "sbt" -t "sbt test" -m "Compilation failed; tests didn't run."`
    elsif line.strip.match /Error running test\:/
      puts line
      `growlnotify --image "images/scalalogo-red.png" --name "sbt" -t "sbt test" -m "Tests fail."`
    else
      puts line
    end
  end
end
